name: Deploy to Minio

on:
  push:
    branches: ['release/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2


      - name: Build Release APK
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          MINIO_ACCESS_KEY_ANDROID: "UE5qIJj1lMzX9XEdrAI2"
          MINIO_SECRET_KEY_ANDROID: "4l540nk5IJsuvrUTasPqHlQtKuu92bOfc3gy2sNm"
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > keystore.jks
          echo "$KEYSTORE_BASE64" | base64 -d > app/keystore.jks
          chmod 600 keystore.jks
          chmod 600 app/keystore.jks
          chmod +x gradlew
          ./gradlew :app:assembleRelease \
            -Pandroid.injected.signing.store.file=keystore.jks \
            -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD \
            -PMINIO_ACCESS_KEY_ANDROID=$MINIO_ACCESS_KEY_ANDROID \
            -PMINIO_SECRET_KEY_ANDROID=$MINIO_SECRET_KEY_ANDROID

      - name: Upload to Minio
        env:
          MINIO_URL: ${{ secrets.MINIO_URL }}
          MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
        run: |
          sudo curl -sL https://dl.min.io/client/mc/release/linux-amd64/mc -o /usr/local/bin/mc
          sudo chmod +x /usr/local/bin/mc

          VERSION=${GITHUB_REF#refs/heads/release/}
          echo "Detected version: $VERSION"

          mc alias set myminio $MINIO_URL $MINIO_ACCESS_KEY $MINIO_SECRET_KEY --api s3v4
          mc ls myminio/applications
          mc cp \
          "$GITHUB_WORKSPACE/app/build/outputs/apk/release/app-release.apk" \
          "myminio/applications/release-$VERSION.apk"
